//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string NewsContent { get; set; }
        public string NewsContentPreview { get; set; }
        public System.DateTime PublishTime { get; set; }
        public int AuthorID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
